name: Check for Merge Conflicts
on: [push]


jobs:
  check-conflicts:
    name: check-for-merge-conflicts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Merge Conflict finder
        uses: ./.github/workflows/github-actions-demo.yml.

