---
name: Merge check in PR
on:
  pull_request :
    types: [synchronize,opened,reopened]

jobs:
  merge-check:
    permissions:
      contents: read
      pull-requests: write
    name: merge_check_in_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge check in Pull Request
        uses: tikmirumian/merge-status-labeler@v1.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}