name: Check for Merge Conflicts
on: [push]


jobs:
  check-conflicts:
    name: check-for-merge-conflicts
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Check for Merge Conflicts
        id: check_conflicts
        run: |
          echo "Fetching PR details"
          PR_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}")
          
          MERGEABLE_STATE=$(echo "$PR_RESPONSE" | jq -r .mergeable_state)
          
          echo "PR mergeable state: $MERGEABLE_STATE"
          
          if [[ "$MERGEABLE_STATE" == "dirty" ]]; then
            echo "::error::Merge conflicts detected. Please resolve the conflicts and update the pull request."
            exit 1
          else
            echo "No merge conflicts detected."
          fi