name: Check for Merge Conflicts
on: [push]


jobs:
  check-conflicts:
    name: check-for-merge-conflicts
    runs-on: ubuntu-latest
    steps:
          # Checkout the source code so we have some files to look at.
        - uses: actions/checkout@v2
          # Run the actual merge conflict finder
        - name: Merge Conflict finder
          uses: olivernybroe/action-conflict-finder@v2.0
