name: Check for Merge Conflicts
on: [push]


jobs:
  check-conflicts:
    name: check-for-merge-conflicts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Check for Merge Conflicts
        id: check_conflicts
        run: |
          # Set the base and head branches
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH=${{ github.event.pull_request.head.ref }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.repository }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          
          # Fetch the base branch
          git fetch origin $BASE_BRANCH
          
          # Check merge conflicts
          git merge-base --is-ancestor origin/$BASE_BRANCH $HEAD_BRANCH || {
            echo "::error::Merge conflicts detected. Please resolve the conflicts and update the pull request."
            exit 1
          }
          
          echo "No merge conflicts detected."